spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: giotse_dev@giotse.com
    password: $senha_DEV_23
    url: jdbc:mysql://localhost:3306/stweardDb?createDatabaseIfNotExist=true
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update